conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

product/urls.py
from django.conf.urls import url

from product.views import *

urlpatterns = [



      url(r'price/log/(?P<pk>[\w]+)/$', ProductVariationPriceLogListView.as_view(), name='price_log_list'),
      url(r'price/request/(?P<pk>[\w]+)/$', get_product_price, name='product_price'),
      url(r'price/list/$', ProductVariationPriceListView.as_view(), name='price_list'),
      url(r'price/create/$', ProductVariationPriceCreateView.as_view(), name='price_create'),
      url(r'price/(?P<pk>[\w]+)/$', ProductVariationPriceUpdateView.as_view(), name='price_edit'),
      url(r'variation/list/$', ProductVariationListView.as_view(), name='variation_list'),
      url(r'variation/create/$', ProductVariationView.as_view(), name='variation_create'),
      url(r'variation/(?P<pk>[\w]+)/$', ProductVariationView.as_view(), name='variation_edit'),
      url(r'unit/list/$', ProductUnitListView.as_view(), name='unit_list'),
      url(r'unit/create/$', ProductUnitCreateView.as_view(), name='unit_create'),
      url(r'unit/(?P<pk>[\w]+)/$', ProductUnitUpdateView.as_view(), name='unit_edit'),
]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls
from stock import urls as stock_urls

from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^stock/', include(stock_urls, namespace='stock')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=25, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product'
    
    def product_variation(self):
        return ProductVariation.objects.filter(product=self)

    def __unicode__(self):
        return self.name
    

class ProductUnit(models.Model):
    name = models.CharField(max_length=25, unique=True)
    code = models.CharField(max_length=3, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_units'
        verbose_name = 'Product Unit'
        verbose_name_plural = 'Product Units'
        
    
    def __unicode__(self):
        return self.name
    

class ProductVariation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    unit = models.ForeignKey(ProductUnit, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation'
        verbose_name = 'Product'
        verbose_name_plural = 'Product'
        unique_together = ['product', 'name']
           
    def __unicode__(self):
        return self.name
    

class ProductVariationPrice(models.Model):
    product = models.ForeignKey(ProductVariation, related_name='variation_price', on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        unique_together = ['product', 'unit']
        
    def __unicode__(self):
        return "%s" % self.product


class ProductVariationPriceLog(models.Model):
    product = models.ForeignKey(ProductVariation, on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price_log'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        
    def __unicode__(self):
        return "%s" % self.product


@receiver(post_save, sender=ProductVariationPrice)
def save_price_log(sender, instance, **kwargs):
    ProductVariationPriceLog.objects.create(product=instance.product,
                                            price=instance.price,
                                            unit=instance.unit,
                                            created_by=instance.created_by)

product/forms.py
from django import forms

from conf.utils import bootstrapify
from product.models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name']


class ProductUnitForm(forms.ModelForm):
    class Meta:
        model = ProductUnit
        fields = ['name', 'code']
        
        
class ProductVariationForm(forms.ModelForm):
    class Meta:
        model = ProductVariation
        fields = ['name', 'unit']


class ProductVariationPriceForm(forms.ModelForm):
    class Meta:
        model = ProductVariationPrice
        fields = ['product', 'unit', 'price']

       

bootstrapify(ProductForm)
bootstrapify(ProductUnitForm)
bootstrapify(ProductVariationForm)
bootstrapify(ProductVariationPriceForm)

product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.forms.formsets import formset_factory, BaseFormSet
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.generic import View, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db import transaction

from django.contrib.auth.models import User, Group

from conf.utils import log_debug, log_error
from product.models import *
from product.forms import *
from userprofile.models import Profile, AccessLevel
from product.api.fanumera import FamuneraAPI


class ExtraContext(object):
    extra_context = {}

    def get_context_data(self, **kwargs):
        context = super(ExtraContext, self).get_context_data(**kwargs)
        context['active'] = ['_union_prod']
        context['title'] = 'Country'
        context.update(self.extra_context)
        return context
    

class ProductUnitListView(ExtraContext, ListView):
    model = ProductUnit
    
    def get_context_data(self, **kwargs):
        context = super(ProductUnitListView, self).get_context_data(**kwargs)
        context['active'].append('__unit')
        return context


class ProductUnitCreateView(ExtraContext, CreateView):
    model = ProductUnit
    form_class = ProductUnitForm
    template_name = "product/productunit_form.html"
    success_url = reverse_lazy('product:unit_list')
    # 
    # def form_valid(self, form):
    #     form.instance.created_by = self.request.user
    #     return super(ProductCreateView, self).form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(ProductUnitCreateView, self).get_context_data(**kwargs)
        context['active'].append('__unit')
        return context
    

class ProductUnitUpdateView(ExtraContext, UpdateView):
    model = ProductUnit
    form_class = ProductUnitForm
    template_name = "product/productunit_form.html"
    success_url = reverse_lazy('product:unit_list')
    # 
    # def form_valid(self, form):
    #     form.instance.created_by = self.request.user
    #     return super(ProductUpdateView, self).form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(ProductUnitUpdateView, self).get_context_data(**kwargs)
        context['active'].append('__unit')
        return context
    
    
class ProductVariationListView(ExtraContext, ListView):
    model = Product
    template_name = "product/productvariation_list.html"
    
    def get_context_data(self, **kwargs):
        context = super(ProductVariationListView, self).get_context_data(**kwargs)
        context['active'].append('__product')
        return context
    
    
class ProductVariationView(View):
    template_name = "product/product_variation_form.html"
    
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        prod = None
        var = None
        initial = None
        extra=1
        try:
            if pk:
                extra = 0
                prod = Product.objects.get(pk=pk)
                pvars = ProductVariation.objects.filter(product=prod)
                initial = [{'name': x.name, 'unit': x.unit} for x in pvars]
        except Exception as e:
            log_error()
            return redirect('product:variation_list')
        product_form = ProductForm(instance=prod)
        variation_form = formset_factory(ProductVariationForm, formset=BaseFormSet, extra=extra)
        variation_formset = variation_form(prefix='variation', initial=initial)
        data = {'form': product_form,
                'variation_formset': variation_formset,
                'active': ['_union_prod', '__product']}
        return render(request, self.template_name, data)
    
    def post(self, request, *args, **kwargs ):
        pk = self.kwargs.get('pk')
        prod = None
        var = None
        initial = None
        extra=1
        try:
            if pk:
                extra=1
                prod = Product.objects.get(pk=pk)
                pvars = ProductVariation.objects.filter(product=prod)
                initial = [{'name': x.name, 'unit': x.unit} for x in pvars]
        except Exception as e:
            log_error()
            return redirect('product:variation_list')
        product_form = ProductForm(request.POST, instance=prod)
        variation_form = formset_factory(ProductVariationForm, formset=BaseFormSet, extra=extra)
        variation_formset = variation_form(request.POST, prefix='variation')
        if product_form.is_valid() and variation_formset.is_valid():
            try:
                with transaction.atomic():
                    p = product_form.save(commit=False)
                    p.created_by = request.user
                    p.save()
                    if pk:
                        ProductVariation.objects.filter(product=p).delete()
                    for variation_form in variation_formset:
                        v = variation_form.save(commit=False)
                        v.product = p
                        v.created_by = request.user
                        v.save()
                return redirect('product:variation_list')
            except Exception as e:
                log_error()
        data = {'form': product_form,
                'variation_formset': variation_formset,
                'active': ['_union_prod', '__product']}
        return render(request, self.template_name, data)

# Variation Price
class ProductVariationPriceCreateView(ExtraContext, CreateView):
    model = ProductVariationPrice
    form_class = ProductVariationPriceForm
    template_name = "product/productvariationprice_form.html"
    success_url = reverse_lazy('product:price_list')
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(ProductVariationPriceCreateView, self).form_valid(form)
    
    
    def get_context_data(self, **kwargs):
        context = super(ProductVariationPriceCreateView, self).get_context_data(**kwargs)
        context['active'].append('__price')
        return context
    

class ProductVariationPriceUpdateView(ExtraContext, UpdateView):
    model = ProductVariationPrice
    form_class = ProductVariationPriceForm
    template_name = "product/productvariationprice_form.html"
    success_url = reverse_lazy('product:price_list')
    # 
    # def form_valid(self, form):
    #     form.instance.created_by = self.request.user
    #     return super(ProductUpdateView, self).form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(ProductVariationPriceUpdateView, self).get_context_data(**kwargs)
        context['active'].append('__price')
        return context
    
    
class ProductVariationPriceListView(ExtraContext, ListView):
    model = ProductVariationPrice
    template_name = "product/productvariationprice_list.html"
    
    def get_context_data(self, **kwargs):
        context = super(ProductVariationPriceListView, self).get_context_data(**kwargs)
        context['active'].append('__price')
        return context
    

class ProductVariationPriceLogListView(ExtraContext, ListView):
    model =  ProductVariationPriceLog
    ordering = '-create_date'
    template_name = "product/productvariationpricelog_list.html"
    
    def get_queryset(self):
        qs = super(ProductVariationPriceLogListView, self).get_queryset()
        if self.kwargs.get('pk'):
            qs = qs.filter(product__pk=self.kwargs.get('pk'))
        return qs
    
    def get_context_data(self, **kwargs):
        context = super(ProductVariationPriceLogListView, self).get_context_data(**kwargs)
        context['active'].append('__price')
        return context
    
def get_product_price(request, pk):
    try:
        pp = ProductVariationPrice.objects.get(product=pk)
        return JsonResponse({"price": pp.price})
    except Exception:
        return JsonResponse({"price": "error"})
   

product/templates/product/product_variation_form.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Product</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.name input_group_add_on='<i class="uk-input-group-icon uk-icon-hashtag"></i>' %}
                    </div>
                    <div class="uk-width-medium-1-2">
                    </div>
                </div>
                <hr>
                 <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-1">
                        
                        <legend>Product Variation</legend>
                        {{ variation_formset.management_form }}
                        {% for form in variation_formset %}
                        {% include "error_template.html" with form=form %}
                            <div class="link-formset">
                                <div class="uk-grid" data-uk-grid-margin>
                                    <div class="uk-width-medium-1-3">
                                        {% include "form/field.html" with field=form.name input_group_add_on='<i class="uk-input-group-icon uk-icon-hashtag"></i>' %}
                                    </div>
                                    <div class="uk-width-medium-1-3">
                                        {% include "form/field.html" with field=form.unit input_group_add_on='<i class="uk-input-group-icon uk-icon-hashtag"></i>' %}
                                    </div>
                                    
                                </div>
                              </div>
                        {% endfor %}
                                 
                    </div>
                    
                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
    <script src="{% static 'bower_components/jquery.formset.js' %}"></script>
    <script>
    $('.link-formset').formset({
        addText: 'add + ',
        deleteText: 'remove -',
        prefix : 'variation'
    });

    $('.link-formset-2').formset({
        addText: 'add + ',
        deleteText: 'remove -',
        prefix: 'patterns'
    });
</script>
    
    
{% endblock %}

product/templates/product/productunit_form.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Product Unit</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.name input_group_add_on='<i class="uk-input-group-icon uk-icon-key"></i>' %}
                                    
                    </div>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.code input_group_add_on='<i class="uk-input-group-icon uk-icon-key"></i>' %}
                        
                    </div>
                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

product/templates/product/productunit_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product Unit List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:unit_create' %}" class="md-btn md-btn-success uk-float-right">Add Product Unit</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                       
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                
                                <td>
                                    <a href="{% url 'product:unit_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                    <a href="{% url 'product:unit_edit' item.id %}" class="md-btn md-btn-primary md-btn-wave waves-effect waves-button uk-float-right">Detail</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariation_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:variation_create' %}" class="md-btn md-btn-success uk-float-right">Add Product</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Product</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>
                                   
                                    {% for variation in item.product_variation %}
                                        <div><strong>- {{ variation }}</strong><div>
                                    {% endfor %}
                                
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:variation_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariationprice_form.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Breed Price</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.product input_group_add_on='<i class="uk-input-group-icon uk-icon-tags"></i>' %}
                                    
                    </div>
                   
                </div>
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.price input_group_add_on='<i class="uk-input-group-icon uk-icon-money"></i>' %}
                                    
                    </div>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=form.unit input_group_add_on='<i class="uk-input-group-icon uk-icon-balance-scale"></i>' %}
                        
                    </div>
                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariationprice_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product Price List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:price_create' %}" class="md-btn md-btn-success uk-float-right">Add Price</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.product }}</td>
                                <td>
                                  {{ item.price }} per {{ item.unit }}<div>
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:price_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Adjust</a>
                                   <a href="{% url 'product:price_log_list' item.product.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Price Log</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariationpricelog_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">{{ breed }} Price Log List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:price_list' %}" class="md-btn md-btn-success uk-float-right">Price List</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Breed</th>
                        <th>Price</th>
                        <th>Changed By</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.breed }}</td>
                                <td>
                                  {{ item.price }} per {{ item.unit }}<div>
                                </td>
                                <td>{{ item.created_by }}</td>
                                <td>{{ item.update_date }}</td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}